# Generated by Django 5.0.3 on 2024-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_auto_20240311_0318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Scheme Discription"
            ),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="email",
            field=models.EmailField(max_length=277, verbose_name="Scheme URL"),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Scheme Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
